name: Playwright Tests
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install PM2
      run: npm install -g pm2
    - name: Install dependencies
      run: pnpm install
    - name: Install Playwright Browsers
      run: pnpm dlx playwright install --with-deps
    - name: Start Localhost
      run: pm2 start pnpm -- dev
    - name: Run Playwright tests
      run: pnpm dlx playwright test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
