name: Playwright Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install pnpm
      run: npm install -g pnpm
    - name: Install PM2
      run: npm install -g pm2
    - name: Install dependencies
      run: pnpm install
    - name: Read pnpm-lock file
      id: pnpm-lock-json
      uses: jbutcher5/read-yaml@1.6
      with:
        file: "./pnpm-lock.yaml"
        key-path: '["devDependencies", "@playwright/test"]'
    - name: Install Playwright Browsers
      run: pnpm dlx playwright@${{ steps.pnpm-lock-json.outputs.data }} install --with-deps
    - name: Start Localhost
      run: pm2 start pnpm -- dev
    - name: Run Playwright tests
      run: pnpm dlx playwright@${{ steps.pnpm-lock-json.outputs.data }} test
    - uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
